version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sensor_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - sensor_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sensor_app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - sensor_network
    command: python src/load_data.py

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sensor_test
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    networks:
      - sensor_network
    command: python src/test_performance.py

networks:
  sensor_network:
    driver: bridge

volumes:
  mongodb_data: 
