version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: sensor_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.5", "--setParameter", "diagnosticDataCollectionEnabled=false"]
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_app
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    profiles:
      - app
      - performance-test
      - index-test
      - csv-test
      - comprehensive-test

  performance-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_performance_test
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}_performance_test
    command: python src/test_performance.py
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    profiles:
      - performance-test

  index-performance-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_index_test
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}_index_test
    command: python src/test_index_performance.py
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - index-test

  csv-reading-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor_csv_test
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=${MONGODB_DB}_csv_test
    command: python src/test_csv_reading.py
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - csv-test

  comprehensive-optimization-test:
    build: .
    container_name: comprehensive-optimization-test
    volumes:
      - ./data:/app/data
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB=sensor_data_comprehensive_test
    command: python src/test_comprehensive_optimization.py
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    profiles:
      - comprehensive-test

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
